site_name: RWoT DIR Launchpad
remote_branch: master
site_url: https://infominer.id/yest
repo_url: https://github.com/infominer33/yest
repo_name: infominer33/yest
edit_uri: 

site_favicon: 'img/favicon.ico'
copyright: "All of the contents of this directory are licensed [Creative Commons CC-BY](docs/LICENSE-CC-BY-4.0/) their contributors, unless otherwise noted."

theme: windmill
use_directory_urls: true

plugins:
    - awesome-pages:
        filename: .index
        collapse_single_pages: true
    - search 


extra:
  article_nav_top: false
  article_nav_bottom: false
